application: your-app-id
version: master
runtime: go
api_version: go1

handlers:
  # - url: /tailbone.(.*).js
  #   static_files: tailbone/js/tailbone.\1.js
  #   upload: tailbone/js/.*

  # - url: /_ah/channel/(dis)?connected/
  #   script: _go_app

  # - url: /api/.*
  #   script: _go_app

  # this links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  # - url: (/?.*)/
  #   static_files: client/app\1/index.html
  #   upload: client/app(.*)/index.html
  # - url: /
  #   static_dir: client/app

  - url: /.*
    script: _go_app

  - url: /_ah/spi/.*
    script: _go_app

# builtins:
#   - appstats: on
#   - deferred: on
#   - admin_redirect: on
#   - remote_api: on

# inbound_services:
#   - warmup
#   - channel_presence

# pagespeed:
#   enabled_rewriters:
#   - MinifyCss
#   disabled_rewriters:
#   - LazyloadImages
