application: your-app-id
version: master
runtime: python27
api_version: 1
threadsafe: true

includes:
  ## Base includes, authentication, and combined /tailbone.js file
  - tailbone
  ## Qunit tests (only works when running locally)
  - tailbone/test
  ## Extra admin commands and interfaces (not done yet)
  # - tailbone/admin
  ## Upload files to blobstore (TODO: also allow cloud storage)
  - tailbone/files
  ## Listen to and bind to global events with javascript and the channel api
  - tailbone/events
  ## Send direct messages between clients with the channel api
  - tailbone/messages
  ## Add the users location in headers via geoip lookup
  # - tailbone/geoip
  ## Full text search must provide a searchable.json at the root level
  - tailbone/search
  ## Simple reverse proxy sometimes useful for cors purposes (note: don't use if you don't have to it
  ## will cost you bandwidth and has no auth)
  # - tailbone/proxy
  ## Clocksync simple synchronization of clocks
  - tailbone/clocksync
  ## Websocket+WebRTC based mesh server with rooms and load balancing
  - tailbone/compute_engine/mesh
  ## Protect all html pages with a simple password, modify in appengine_config.py
  - tailbone/static_protected
  ## Order in this list is important for restful and pathrewrite, they must be last.
  ## Restful resources
  - tailbone/restful
  ## Any path without a file extension not in /api gets the app/client/index.html text. Useful for
  ## html5 applications that use the history api to write their paths.
  # - tailbone/pathrewrite

  # This links everything else in your client/app folder to be served
  # Change this to something else if your public folder is not client/app
  # if you use tailbone/static_protected you need to turn this off
  # - tailbone/static


builtins:
  - appstats: on
  - deferred: on
  - admin_redirect: on
  - remote_api: on

# Neccessary only for the JWT Credentials when developing locally and using the compute_engine module
libraries:
  - name: "pycrypto"
    version: "latest"

inbound_services:
  - warmup
  - channel_presence

skip_files:
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*

pagespeed:
  # domains_to_rewrite:
  # - slowdomain.com
  # url_blacklist:
  # - http://myapp.com/dontoptomize/*
  enabled_rewriters:
  - MinifyCss
  disabled_rewriters:
  - LazyloadImages
  # Available rewriters
  # - ProxyCss # - default
  # - ProxyImages # - default
  # - ProxyJs # - default
  # - ConvertMetaTags # - default
  # - InlineCss # - default
  # - InlineJs
  # - InlineImages
  # - InlinePreviewImages # - default
  # - CollapseWhitespace
  # - CombineHeads
  # - ElideAttributes
  # - RemoveComments
  # - RemoveQuotes
  # - LeftTrimUrls

  # - CombineCss # - default
  # - MoveCssToHead # - default
  # - MinifyCss

  # - WebpOptimization # - default
  # - ImageConvertToJpeg # - default
  # - ImageRecompressJpeg # - default
  # - ImageProgressiveJpeg # - default
  # - ImageRecompressPng # - default
  # - ImageStripMetadata # - default
  # - ImageStripColorProfile # - default
  # - ImageResize # - default
  # - LazyloadImages # - default
  # - ImageAddDimensions

  # - CombineJs # - default
  # - JsOptimize # - default
  # - DeferJs

